management:
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  h2:
    console:
      enabled: true
      path: /h2-console  # 기본 경로는 /h2-console
  datasource:
    url: jdbc:h2:mem:testdb  # 메모리 DB 사용 시 기본 설정
    driver-class-name: org.h2.Driver
    username: sa
    password:

# 로그를 보고 싶을 경우
logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
